export const FETCH_TOP_RATED_MOVIES = "FETCH_TOP_RATED_MOVIES";
export const FETCH_TRENDING_MOVIES = "FETCH_TRENDING_MOVIES";
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_UPCOMING = "FETCH_UPCOMING";